    '''
    url(r'^index/$', 'TPVpnapp.views.mainPage'),
    url(r'^logout/$', 'TPVpnapp.views.logoutSession'),
    url(r'^new_product/$', 'TPVpnapp.views.newProduct'),
    url(r'^index/(?P<sale_id>[0-9]+)/$', 'TPVpnapp.views.actualSale'),
    url(r'^deleteItem/(?P<sale_id>[0-9]+)/(?P<item_id>[0-9]+)/$', 'TPVpnapp.views.deleteItem'),
    url(r'^deleteSale/(?P<sale_id>[0-9]+)/$', 'TPVpnapp.views.deleteSale'),
    url(r'^new_client/$', 'TPVpnapp.views.newClient'),
    url(r'^deleteClient/(?P<sale_id>[0-9]+)/$', 'TPVpnapp.views.deleteClient'),
    url(r'^products/$', 'TPVpnapp.views.listProducts'),
    url(r'^products/delete/(?P<product_id>[0-9]+)/$', 'TPVpnapp.views.deleteProduct'),
    url(r'^modProd/(?P<product_id>[0-9]+)/$', 'TPVpnapp.views.modifyProduct'),
    url(r'^clients/$', 'TPVpnapp.views.listClients'),
    url(r'^modCli/(?P<pk>.*)/$', 'TPVpnapp.views.modClient'),
    url(r'^client_profile/(?P<pk>.*)/$', 'TPVpnapp.views.clientProfile'),
    '''
